## Question 1

In [1]:
import numpy as np
print(np.array(range(2,50,3)))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question 2

In [2]:
import numpy as np
a=list()
b=list()
for i in range(0,5):
    a.append(int(input()))
for i in range(0,5):
    b.append(int(input()))
# convert them to array
A1=np.array(a)
A2=np.array(b)
print(A1)
print(A2)
# concatenate and print array
print(np.concatenate((A1,A2),axis=None))
# Sorting arrays
print(np.sort(A1))
print(np.sort(A2))

10
2
45
32
85
46
52
1
23
2
[10  2 45 32 85]
[46 52  1 23  2]
[10  2 45 32 85 46 52  1 23  2]
[ 2 10 32 45 85]
[ 1  2 23 46 52]


## Question 3

In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.size)

2
6


## Question 4

In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print("1D Array :")
print(a)
b=np.reshape(a,(2,3))
print("2D Array :")
print(b)

1D Array :
[1 2 3 4 5 6]
2D Array :
[[1 2 3]
 [4 5 6]]
